name: SAWScript
on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc: ["8.6.5", "8.8.3"]
        include:
          - os: macos-latest
            ghc: 8.6.5
            continue-on-error: true
          - os: macos-latest
            ghc: 8.8.3
            continue-on-error: true
    name: SAWScript - GHC v${{ matrix.ghc }} - ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          git submodule update --init
          git -C deps/abcBridge submodule update --init

      - uses: actions/setup-haskell@v1
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}
          enable-stack: true

      - uses: actions/cache@v2
        name: Cache cabal store
        with:
          path: |
            ${{ steps.setup-haskell.outputs.cabal-store }}
            dist-newstyle
          key: cabal-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/cabal.GHC-*') }}-${{ github.sha }}
          restore-keys: |
            cabal-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/cabal.GHC-*') }}-
            cabal-${{ runner.os }}-${{ matrix.ghc }}-

      - shell: bash
        run: .github/ci.sh build_abc

      - shell: bash
        run: .github/ci.sh build

      - shell: bash
        run: .github/ci.sh install_system_deps
        env:
          Z3_VERSION: "4.8.7"
          CVC4_VERSION: "4.1.8"
          YICES_VERSION: "2.6.2"

      - uses: actions/setup-java@v1
        with:
          java-version: "8"
          java-package: jdk
          architecture: x64

      - shell: bash
        id: test
        continue-on-error: ${{ matrix.continue-on-error }}
        name: Integration Tests
        run: |
          mkdir -p ~/.stack
          echo "system-ghc: true" >> ~/.stack/config.yaml
          .github/ci.sh test_dist
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "saw-${{ runner.os }}-${{ matrix.ghc }}"
          path: s2nTests/bin/saw

      - shell: bash
        if: "steps.test.outcome == 'failure'"
        name: Warn if tests failed
        run: echo "::error ::Test Suite Failed. Pipeline allowed to pass until tests are reliable."
  s2n-tests:
    name: "Test s2n proofs"
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - s2n-name: "HMAC"
            s2n-target: hmac
          - s2n-name: "DRBG"
            s2n-target: drbg
          - s2n-name: "SIKE"
            s2n-target: sike
          - s2n-name: "BIKE"
            s2n-target: bike
          - s2n-name: "TLS"
            s2n-target: tls
          - s2n-name: "HMAC Failure"
            s2n-target: hmac-failure
    steps:
      - name: Download previously-built SAW 
        uses: actions/download-artifact@v2
        with:
          name: "saw-ubuntu-latest-8.6.5"
      - shell: bash
        name: "s2n tests: ${{ matrix.s2n-name }}"
        working-directory: s2nTests
        run: |
          docker-compose run ${{ matrix.s2n-target }}
