name: Type-check handwritten and generated Coq files
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    branches: [master]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # coq-bits does not support coq >= 8.13 yet
        coq: [8.12.2, 8.11.2, 8.10.2]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: saw-core-coq - ${{ matrix.os }} - coq-${{ matrix.coq }}
    env:
      COQ_VERSION: ${{ matrix.coq }}
      # coq-bits claims to support < 4.10 only
      OCAML_VERSION: 4.09.x
      COQBITS_VERSION: 1.0.0
    steps:
      - uses: actions/checkout@v2

      - name: Set up ocaml and opam
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ env.OCAML_VERSION }}

      - name: Install coq
        shell: bash
        run: |
          opam pin add coq ${{ env.COQ_VERSION }}
          opam install --unlock-base -y coq

      - name: Install coq-bits
        shell: bash
        run: |
          opam repo add coq-released https://coq.inria.fr/opam/released
          opam install --unlock-base -y "coq-bits=$COQBITS_VERSION"

      - name: Build saw-core-coq/coq
        shell: bash
        working-directory: saw-core-coq/coq
        run: |
          opam exec -- coq_makefile -f _CoqProject -o Makefile.coq
          opam exec -- make -j2
